# Generated by Django 4.2.16 on 2024-09-25 02:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tellings", "0001_initial"),
        ("book_creation", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("payments", "0001_initial"),
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="storyprompt",
            name="telling_record",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="tellings.tellingrecord"
            ),
        ),
        migrations.AddField(
            model_name="page",
            name="book",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pages",
                to="book_creation.book",
            ),
        ),
        migrations.AddField(
            model_name="book",
            name="child",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="books",
                to="accounts.child",
            ),
        ),
        migrations.AddField(
            model_name="book",
            name="paid_service",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="payments.paidservice",
            ),
        ),
        migrations.AddField(
            model_name="book",
            name="story_prompt",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="books",
                to="book_creation.storyprompt",
            ),
        ),
        migrations.AddField(
            model_name="book",
            name="story_template",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="books",
                to="book_creation.storytemplate",
            ),
        ),
        migrations.AddField(
            model_name="book",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="books",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
