# Generated by Django 4.2.16 on 2024-10-01 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book_creation", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="book",
            name="pdf_file_path",
        ),
        migrations.AddField(
            model_name="book",
            name="pdf_file",
            field=models.BinaryField(null=True),
        ),
        migrations.AlterField(
            model_name="book",
            name="last_downloaded_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="book",
            name="pdf_generated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
