# Generated by Django 4.2.16 on 2024-10-24 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tellings", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tellingrecord",
            name="telling_date",
            field=models.DateField(),
        ),
    ]
