# Generated by Django 4.2.16 on 2024-10-24 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("book_creation", "0003_remove_book_pdf_file_path_book_pdf_file_and_more"),
        ("tellings", "0002_alter_tellingrecord_telling_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tellingrecord",
            name="book",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="telling_records",
                to="book_creation.book",
            ),
        ),
        migrations.AlterField(
            model_name="tellingrecord",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
    ]
